<a href="https://colab.research.google.com/github/AshnaWiar/Recommender/blob/main/content_base_filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Todo's

*   This method is using Tf-idf (comparing simliarities between words)
*   need to recommend tho's who fit the requirements i.e. grade 2 Java developer.

In [ ]:
import plotly.express as px
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

wuzzuf_df = pd.read_csv('/content/Wuzzuf_Jobs.csv')

In [ ]:
developer_vacancies = wuzzuf_df.loc[wuzzuf_df['Title'].str.lower().str.contains('developer')]
print(developer_vacancies.shape)

(385, 8)

In [ ]:
developer_vacancies.head()

                                          Title                      Company     Location       Type           Level         YearsExp Country                                             Skills
5   Senior .NET Developer (Desktop Application)                        Dexef        Maadi  Full Time     Experienced   3-5 Yrs of Exp   Cairo  ASP.NET, Desktop Development, Information Tech...
29                     Sr. JavaScript Developer                Longman Egypt   Alexandria  Full Time     Experienced  5-10 Yrs of Exp   Egypt  Information Technology (IT), Computer Science,...
32                  Senior JavaScript Developer                Longman Egypt         Giza  Full Time     Experienced  5-10 Yrs of Exp    Giza  Computer Science, Information Technology (IT),...
73                         Curriculum Developer         Almotahida Education        Cairo  Full Time  Work From Home    2+ Yrs of Exp   Egypt  Curriculum Development, Education, Teaching, S...
93                         Senior iOS Developer  Integrated Technology Group        Cairo  Full Time     Experienced   4-6 Yrs of Exp   Egypt  Mobile Applications, Information Technology (I...

In [ ]:
developer_skills = sorted(
    np.concatenate(
      developer_vacancies['Skills'].str.split(', ').tolist()
    )
)

print(list(dict.fromkeys(developer_skills)))

['.NET', '.NET Core', '.NET Development', '.Net', '.Net Core', '.Net Framework', '.Net core', '2 Vacancies', '2+ Yrs of Exp', '2-10 Yrs of Exp', '3 Vacancies', '3+ Yrs of Exp', '3D', '4 Vacancies', 'ABAP', 'ADF', 'ADO.NET', 'AJAX', 'API', 'APIs', 'AR', 'ASP.NET', 'ASP.NET MVC', 'ASP.NET MVC,', 'ASP.Net', 'AWS', 'AX', 'Active Directory', 'Adobe Illustrator', 'Adobe Indesign', 'Adobe Photoshop', 'Adobe Suite', 'Adobe XD', 'Advertising', 'Affiliate Management System', 'Agile', 'Ajax', 'Algorithms', 'Amazon', 'Amazon Travel', 'Andriod', 'Android', 'Android Design', 'Android Developer', 'Android Development', 'Android OS', 'Android SDK', 'Android Studio', 'Angular', 'Angular 2+', 'Angular 7', 'Angular 7+', 'Angular CLI', 'Angular JS', 'Angular Js', 'Angular.JS', 'Angular.js', 'Angular5+', 'AngularJS', 'AngularJS 2', 'AngularJs', 'Apollo', 'App Store', 'Appium', 'Application', 'Applications', 'Apps', 'ArcGIS', 'Asp.Net', 'Authorize.net', 'Azure', 'B2B', 'BACKEND', 'BDD', 'BI', 'BLoC', 'BOM', 'BPM', 'Back End', 'Back-End', 'Back-End Developer', 'Back-End Development', 'Backend', 'Backend Developer', 'Backend Development', 'Biology', 'Bitbucket', 'Bootstrap', 'Bootstrap 4', 'Branding', 'Business Administration', 'Business Analysis', 'Business Development', 'Business Intelligence', 'C#', 'C#.Net', 'C++', 'C/AL', 'C/C++', 'C/Side', 'CD', 'CI', 'CI/CD', 'CLI', 'CMS', 'CORE .Net', 'CRM', 'CSOM', 'CSS', 'CSS3', 'ChartJS', 'Chemistry', 'Cloud', 'Cloud Technology', 'Cocoa Touch', 'CocoaPods', 'Code Versioning', 'Code Versioning Tools', 'CodeIgniter Framework', 'Codeigniter', 'Coding', 'Communication', 'Communication Skills', 'Computer Engineering', 'Computer Hardware', 'Computer Science', 'Computing', 'Configuration', 'Core', 'Core Animation', 'Core Data', 'Corporate Sales', 'Creative', 'Creative/Design/Art', 'Cross Platform', 'Crystal Reports', 'Curriculum Development', 'DART', 'DAX', 'DB2 DBMS', 'DEVELOPER', 'DFD', 'DHTML', 'DNS', 'DOM', 'Dart', 'Data Analytics', 'Data Modeling', 'Data Science', 'Data Structure', 'Data Structures', 'Data Warehouse', 'Data Warehousing', 'Database', 'Database Administration', 'Database Schemas', 'Databases', 'Delphi', 'Design', 'Design Patterns', 'Desktop Development', 'DevOps', 'Developer', 'Development', 'Devexpress', 'Digital Marketing', 'Digital Transformations', 'Django', 'Docker', 'Drupal', 'Dynamics AX 2012', 'Dynamics AX Developer', 'Dynamics CRM', 'DynamoDB', 'E-Commerce', 'E-commerce', 'E-learning', 'E-marketing', 'EHcache', 'EJB', 'ERP', 'ES6', 'ETL', 'Eclipse', 'Education', 'Education/Teaching', 'Educational Games', 'Elastic Search', 'Electrical Power Engineering', 'Electronics', 'Ember.JS', 'Engineering', 'Engineering - Telecom/Technology', 'English', 'Entity Framework', 'Expo', 'Express', 'Express.js', 'ExpressJS', 'FTP', 'FULL STACK', 'Financial Applications', 'Financial Sector', 'Firebase', 'Fix Bugs', 'Flask', 'Flexbox', 'Flutter', 'Flutter Development', 'Flutter Mobile Application', 'Flux/Redux', 'Fragments', 'Frameworks', 'Front End', 'Front End Developer', 'Front-End', 'Front-End Development', 'FrontEnd', 'Frontend', 'Full Stack', 'Full Stack Development', 'Full-Stack', 'Fullstack', 'GIT', 'GITHub', 'GO', 'Game Design', 'Game Developer', 'Game Development', 'Game Studio', 'Git', 'Git AngularJS', 'GitFlow', 'GitHub', 'GitLab', 'Gitflow', 'Github', 'Gitlab', 'Glassfish', 'Google Checkout', 'Google Cloud', 'Gradle', 'GraphQL', 'GraphQL API', 'Graphic Design', 'Gulp', 'HTML', 'HTML 5', 'HTML/CSS', 'HTML5', 'HTTPWatch', 'Hibernate', 'Html 4', 'IBM InfoSphere DataStage', 'IBM MQ', 'IIB Integration', 'IIS', 'IOS', 'ISV Application', 'IT', 'IT/Software Development', 'ITI', 'Iframe', 'Implementation', 'Information Systems', 'Information Technology (IT)', 'Installation/Maintenance/Repair', 'Integration', 'IntelliJ', 'Ionic', 'Ionic 2+', 'Ionic 4', 'J#', 'J2EE', 'JBPM', 'JDBC', 'JPA', 'JQUERY', 'JQuery', 'JS', 'JSF', 'JSOM', 'JSON', 'JScript.NET', 'Java', 'Java 8', 'Java EE', 'Java SE', 'JavaScript', 'Javascript', 'Jenkins', 'Jetpack', 'Jira', 'Json', 'Kanban', 'Karaf', 'Kinect', 'Koa', 'Kotlin', 'Kubernetes', 'LAMP', 'LARAVEL', 'LESS', 'LINQ', 'Lambda AWS', 'Laravel', 'Larvel', 'Leadership', 'Leap Motion', 'Learning Software', 'Linq', 'Linux', 'MCSE', 'MEAN Stack', 'ML/XHTML', 'MS ASP', 'MS SQL', 'MS SQL Server', 'MS-SQL', 'MSSQL', 'MV', 'MVC', 'MVC 5', 'MVC.NET', 'MVP', 'MVVM', 'MYSQL', 'Magento', 'Males Only', 'Males Preferred', 'Management', 'Market Research', 'Marketing', 'Marketing/PR/Advertising', 'Maven', 'Mean Stack', 'MicroServices', 'Microservices', 'Microsoft Dynamics', 'Microsoft Dynamics AX', 'Microsoft Dynamics CRM', 'Microsoft Excel', 'Microsoft Nav Development', 'Microsoft Office', 'Microsoft SQL Server', 'Microsoft visual studio 2015', 'Microsoft.Net', 'Mobile App Developer', 'Mobile Application', 'Mobile Applications', 'Mobile Apps', 'Mobile Developer', 'Mobile Development', 'Mobile development', 'Mongo DB', 'MongoDB', 'MongoDb', 'My SQL', 'MySQL', 'Mysql', 'NG2', 'NODEJS', 'NPM', 'Native', 'Nginx', 'Nintex', 'Nintex Workflow', 'NoSQL', 'Node', 'Node js', 'Node.JS', 'Node.js', 'NodeJS', 'Nodejs', 'Nosql', 'OBIEE', 'OBJECTIVE - C', 'OLAP', 'OOD', 'OOP', 'OSGi', 'Objective C', 'Objective-C', 'Odoo', 'Odoo Modules', 'Offline Storage', 'OpenCart', 'Oracle', 'Oracle ADF', 'Oracle DB', 'Oracle Forms', 'Oracle PL/SQL', 'Oracle SOA', 'Oracle SQL', 'Oracle developer', 'PHP', 'PHP Back-End', 'PHP Laravel', 'PHP developper', 'PHP5', 'PHP5+', 'PL', 'PL/SQL', 'PLSQL', 'Payfort', 'Payments Gateways', 'Paypal', 'Photoshop', 'Physics', 'Plugins', 'PostgreSQL', 'Postgresql', 'Power BI', 'Power BI Development', 'PowerShell', 'Problem Solving', 'Product Development', 'Programmer', 'Programming', 'Project Management', 'Projects', 'Provider', 'Push Notifications', 'Python', 'Quality', 'RAzor', 'RDBMS', 'REST', 'REST API', 'REST APIs', 'RESTful', 'RESTful APIs', 'RESTfulWebServices', 'RPA', 'RPC', 'RWD', 'React', 'React Hooks', 'React JS', 'React Native', 'React-Native', 'React.JS', 'React.js', 'ReactJS', 'ReactJs', 'Reactive', 'Reactjs', 'Realm', 'Redis', 'Redux', 'Rest', 'Restful', 'Restful Web API', 'Ruby', 'Ruby On Rails', 'Rust', 'RxSwift', 'Rxjs', 'SASS', 'SCSS', 'SDK', 'SDLC', 'SE', 'SEO', 'SME', 'SOA', 'SOAP', 'SOLID', 'SQL', 'SQL Server', 'SSRS', 'SVN', 'SWE', 'SaSS', 'SaaS', 'Sales', 'Sales Skills', 'Sales Target', 'Sales/Retail', 'Schemas', 'Science', 'Scrum', 'Selling Marketing Services', 'Senior FrontEnd Developer', 'Servers', 'SharePoint', 'SharePoint 2016/2013/2010', 'SharePoint Administration', 'Slack', 'Software', 'Software Computer Science', 'Software Development', 'Software Engineering', 'Software Sales', 'Software Testing', 'SolidWorks', 'Spring', 'Spring Boot', 'Spring boot', 'Startup', 'Swift', 'Swift 4', 'Swift 5', 'Swift UI', 'Symfony2', 'System Administration', 'System Analysis', 'System Design', 'System Engineering', 'T-SQL', 'TCP/IP & Protocols', 'TDD', 'TFS', 'Teacher', 'Teaching', 'Telecom', 'Telecom Engineering', 'Telecommunication', 'Template Engine', 'TestNG', 'Testing', 'Tomcat', 'Travel', 'Trello', 'Troubleshooting', 'Twig', 'TypeScript', 'Typescript', 'Typescript based API', 'UI', 'UI Design', 'UI Developer', 'UI/UX', 'UIKIT', 'UX', 'Unit Test', 'Unity', 'Unity3D', 'Unix', 'VB', 'VR', 'Version Control', 'Viper', 'Virtual Reality', 'Visual Basic .NET', 'Vue', 'Vue Js', 'Vue.Js', 'VueJS', 'VueJs', 'Vues', 'WCF', 'WCS', 'WFS', 'WMS', 'WPS', 'WSDL', 'Web', 'Web API', 'Web Applications', 'Web Design', 'Web Development', 'Web Forms', 'Web Performance', 'Web Services', 'Web development', 'WebAPI', 'WebRTC', 'Weblogic', 'Webpack', 'Website Development', 'WinForms', 'Windows Server', 'WordPress', 'WordPress Plugin', 'Wordpress', 'Workflow', 'Writing', 'XAML', 'XCTest', 'XCode', 'XML', 'XPath', 'XSLT', 'XSLT/XML', 'Xamarin', 'Xamarin Forms', 'Yaf', 'Yii', 'Zend', 'angular js', 'angulr', 'app development', 'cocoa', 'code', 'conventional coding', 'cross-platform development', 'css', 'e-learning', 'entity framework', 'flutter', 'github', 'html', 'iOS', 'iOS Development', 'jQuery', 'javaScript', 'javascript', 'jquery', 'js', 'laravel', 'machine learning', 'micro services', 'mobile development', 'mongodDB', 'react native', 'senior front-end developer', 'senior frontend developer', 'user experience', 'video processing']

In [ ]:
skill_df = pd.DataFrame(developer_skills, columns=["Skill"]).groupby('Skill').Skill.count()
skill_df = skill_df[skill_df > 2]
skill_df = skill_df.sort_values()

fig = px.bar(skill_df, y='Skill', title="("+str(skill_df.size)+") Developer skill Occurences in vacancies")
fig.update_layout(yaxis={"dtick":10, 'range':[0,100]})
fig.show()

In [ ]:
#@title user skills
skills = [
    "Java 8", "Flutter",
    "ASP.NET", "Python",
    "LINQ", "Angular",
    "LARAVEL", "Laravel",
    "Typescript", "CSS", 
    "HTML", "Bootstrap",
    "JavaScript", "Javascript",
    "C#", "PostgreSQL",
    "PHP", "Dart",
    "Docker", "GIT",
]

skill_dict = dict.fromkeys(skills, 1)

print(skill_dict)

{'Java 8': 1, 'Flutter': 1, 'ASP.NET': 1, 'Python': 1, 'LINQ': 1, 'Angular': 1, 'LARAVEL': 1, 'Laravel': 1, 'Typescript': 1, 'CSS': 1, 'HTML': 1, 'Bootstrap': 1, 'JavaScript': 1, 'Javascript': 1, 'C#': 1, 'PostgreSQL': 1, 'PHP': 1, 'Dart': 1, 'Docker': 1, 'GIT': 1}

Todo


*   improve comparing

In [ ]:
df = developer_vacancies[['Title', 'Skills']]

for skill in skill_dict.keys():
  df.loc[df["Skills"].str.contains(skill), skill] = 1

df = df.fillna(0)

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1684: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
df.head()

                                          Title                                             Skills  Java 8  Flutter  ASP.NET  Python  LINQ  Angular  LARAVEL  Laravel  Typescript  CSS  HTML  Bootstrap  JavaScript  Javascript   C#  PostgreSQL  PHP  Dart  Docker  GIT
5   Senior .NET Developer (Desktop Application)  ASP.NET, Desktop Development, Information Tech...     0.0      0.0      1.0     0.0   0.0      0.0      0.0      0.0         0.0  0.0   0.0        0.0         0.0         0.0  0.0         0.0  0.0   0.0     0.0  0.0
29                     Sr. JavaScript Developer  Information Technology (IT), Computer Science,...     0.0      0.0      0.0     0.0   0.0      0.0      0.0      0.0         0.0  1.0   1.0        0.0         0.0         0.0  0.0         0.0  0.0   0.0     0.0  0.0
32                  Senior JavaScript Developer  Computer Science, Information Technology (IT),...     0.0      0.0      0.0     0.0   0.0      0.0      0.0      0.0         0.0  1.0   1.0        0.0         0.0         0.0  0.0         0.0  0.0   0.0     0.0  0.0
73                         Curriculum Developer  Curriculum Development, Education, Teaching, S...     0.0      0.0      0.0     0.0   0.0      0.0      0.0      0.0         0.0  0.0   0.0        0.0         0.0         0.0  0.0         0.0  0.0   0.0     0.0  0.0
93                         Senior iOS Developer  Mobile Applications, Information Technology (I...     0.0      0.0      0.0     0.0   0.0      0.0      0.0      0.0         0.0  0.0   0.0        0.0         0.0         0.0  0.0         0.0  0.0   0.0     0.0  0.0

In [ ]:
vacancies_matrix = df[df.columns[2:]]
user_matrix = pd.DataFrame(skill_dict, index=[0])


df1_transposed = vacancies_matrix.T
print(user_matrix.shape)
print(df1_transposed.shape)

dot_product = user_matrix.dot(df1_transposed).T
dot_product = dot_product.sort_values(by=0, ascending=False);
dot_product = dot_product[dot_product[0] > 0]

print(dot_product.head())

(1, 20)
(20, 385)
        0
892   6.0
2951  5.0
1290  5.0
3584  5.0
314   5.0

In [ ]:
vacancies_matrix.head()

    Java 8  Flutter  ASP.NET  Python  LINQ  Angular  LARAVEL  Laravel  Typescript  CSS  HTML  Bootstrap  JavaScript  Javascript   C#  PostgreSQL  PHP  Dart  Docker  GIT
5      0.0      0.0      1.0     0.0   0.0      0.0      0.0      0.0         0.0  0.0   0.0        0.0         0.0         0.0  0.0         0.0  0.0   0.0     0.0  0.0
29     0.0      0.0      0.0     0.0   0.0      0.0      0.0      0.0         0.0  1.0   1.0        0.0         0.0         0.0  0.0         0.0  0.0   0.0     0.0  0.0
32     0.0      0.0      0.0     0.0   0.0      0.0      0.0      0.0         0.0  1.0   1.0        0.0         0.0         0.0  0.0         0.0  0.0   0.0     0.0  0.0
73     0.0      0.0      0.0     0.0   0.0      0.0      0.0      0.0         0.0  0.0   0.0        0.0         0.0         0.0  0.0         0.0  0.0   0.0     0.0  0.0
93     0.0      0.0      0.0     0.0   0.0      0.0      0.0      0.0         0.0  0.0   0.0        0.0         0.0         0.0  0.0         0.0  0.0   0.0     0.0  0.0

In [ ]:
user_matrix

   Java 8  Flutter  ASP.NET  Python  LINQ  Angular  LARAVEL  Laravel  Typescript  CSS  HTML  Bootstrap  JavaScript  Javascript  C#  PostgreSQL  PHP  Dart  Docker  GIT
0       1        1        1       1     1        1        1        1           1    1     1          1           1           1   1           1    1     1       1    1

In [ ]:
recommended_vacancies_indexes = list(dot_product.index.values);
recommended_vacancies = developer_vacancies.loc[recommended_vacancies_indexes]

In [ ]:
#@title recommended vacancies
recommended_vacancies[['Title', 'Skills']].head()

                                      Title                                             Skills
892   SharePoint/Workflow Developer - Cairo  Workflow, Application, RPA, Angular Js, ASP.NE...
2951       Senior Full Stack .NET Developer  HTML5, RESTful, MVC, Xamarin, Bootstrap, jQuer...
1290                        UI/UX Developer  UI, UI/UX, Web Development, Bootstrap, jQuery,...
3584                   Full Stack Developer  Computer Science, UI, UX, MVC, PHP, Laravel, j...
314               Senior Back-End Developer  SEO, Design Patterns, Programming, PHP, Larave...

In [ ]:
#@title unsuitable vacancies
developer_vacancies.drop(recommended_vacancies_indexes)[['Title', 'Skills']].head()

                                   Title                                             Skills
73                  Curriculum Developer  Curriculum Development, Education, Teaching, S...
93                  Senior iOS Developer  Mobile Applications, Information Technology (I...
122  Front-End Developer (IOS & Android)  Software Development, Front End, UI/UX, UX, iO...
162                 Junior iOS Developer  Git, Computer Science, Information Technology ...
184       Senior Microsoft Nav Developer  Computer Science, Software Development, Micros...